import type { InsertProject } from "../../shared/validators";

// AI Provider seed configs
export const SEED_AI_PROVIDERS = [
  {
    slug: "anthropic",
    displayName: "Anthropic (Claude)",
    providerType: "anthropic" as const,
    isEnabled: false,
    defaultForRole: "architect" as const,
    modelTiers: { builder: "claude-sonnet-4-6", architect: "claude-opus-4-6" },
    config: {},
    displayOrder: 0,
  },
  {
    slug: "openai",
    displayName: "OpenAI",
    providerType: "openai" as const,
    isEnabled: false,
    modelTiers: { builder: "gpt-4o", architect: "gpt-4o" },
    config: {},
    displayOrder: 1,
  },
  {
    slug: "google",
    displayName: "Google (Gemini)",
    providerType: "google" as const,
    isEnabled: false,
    modelTiers: { builder: "gemini-2.0-flash", architect: "gemini-2.5-pro" },
    config: {},
    displayOrder: 2,
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek",
    providerType: "deepseek" as const,
    isEnabled: false,
    modelTiers: { builder: "deepseek-chat", architect: "deepseek-reasoner" },
    config: { baseUrl: "https://api.deepseek.com/v1" },
    displayOrder: 3,
  },
  {
    slug: "groq",
    displayName: "Groq",
    providerType: "groq" as const,
    isEnabled: false,
    modelTiers: { builder: "llama-3.3-70b-versatile" },
    config: { baseUrl: "https://api.groq.com/openai/v1" },
    displayOrder: 4,
  },
  {
    slug: "kimi",
    displayName: "Kimi (Moonshot)",
    providerType: "kimi" as const,
    isEnabled: false,
    modelTiers: { builder: "moonshot-v1-8k", architect: "moonshot-v1-32k" },
    config: { baseUrl: "https://api.moonshot.cn/v1" },
    displayOrder: 5,
  },
  {
    slug: "replit",
    displayName: "Replit Agent",
    providerType: "replit" as const,
    isEnabled: false,
    defaultForRole: "builder" as const,
    modelTiers: { builder: "replit-agent" },
    config: {},
    displayOrder: 6,
  },
];

export const SEED_PROJECTS: InsertProject[] = [
  {
    slug: "triadblue",
    displayName: "TRIADBLUE",
    description: "Core platform and ecosystem hub",
    githubRepo: "triadblue",
    colorPrimary: "#0000FF",
    colorAccent: "#FF44CC",
    iconUrl: "/assets/brands/triadblue/icon.png",
    status: "active",
    displayOrder: 0,
    visible: true,
    tags: ["core", "platform"],
    subdomainUrl: "triadblue.com",
    productionUrl: "https://triadblue.com",
    syncEnabled: true,
  },
  {
    slug: "consoleblue",
    displayName: "ConsoleBlue",
    description: "Central management dashboard for the TriadBlue ecosystem",
    githubRepo: "consoleblue",
    colorPrimary: "#FF44CC",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/consoleblue/icon.png",
    status: "active",
    displayOrder: 1,
    visible: true,
    tags: ["dashboard", "admin"],
    subdomainUrl: "console.blue",
    productionUrl: "https://console.blue",
    syncEnabled: true,
  },
  {
    slug: "linkblue",
    displayName: "LINKBlue",
    description: "Website monitoring and health tracking panel",
    githubRepo: "linkblue",
    colorPrimary: "#2073E3",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/linkblue/icon.png",
    status: "active",
    displayOrder: 2,
    visible: true,
    tags: ["monitoring", "health"],
    subdomainUrl: "linkblue.triadblue.com",
    productionUrl: "https://linkblue.triadblue.com",
    syncEnabled: true,
  },
  {
    slug: "hostsblue",
    displayName: "hostsblue",
    description: "Web hosting and infrastructure management",
    githubRepo: "hostsblue",
    colorPrimary: "#008060",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/hostsblue/icon.png",
    status: "active",
    displayOrder: 3,
    visible: true,
    tags: ["hosting", "infrastructure"],
    subdomainUrl: "hostsblue.com",
    productionUrl: "https://hostsblue.com",
    syncEnabled: true,
  },
  {
    slug: "swipesblue",
    displayName: "swipesblue",
    description: "Payment processing and transaction management",
    githubRepo: "swipesblue",
    colorPrimary: "#374151",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/swipesblue/icon.png",
    status: "active",
    displayOrder: 4,
    visible: true,
    tags: ["payments", "transactions"],
    subdomainUrl: "swipesblue.com",
    productionUrl: "https://swipesblue.com",
    syncEnabled: true,
  },
  {
    slug: "businessblueprint",
    displayName: "businessblueprint",
    description:
      "AI-powered business planning and digital assessment platform",
    githubRepo: "businessblueprint",
    colorPrimary: "#F97316",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/businessblueprint/icon.png",
    status: "active",
    displayOrder: 5,
    visible: true,
    tags: ["business-planning", "ai", "assessment"],
    subdomainUrl: null,
    productionUrl: null,
    syncEnabled: true,
  },
  {
    slug: "scansblue",
    displayName: "scansblue",
    description: "Security scanning and analysis tools",
    githubRepo: "scanslab",
    colorPrimary: "#A00028",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/scansblue/icon.png",
    status: "development",
    displayOrder: 6,
    visible: true,
    tags: ["security", "scanning"],
    subdomainUrl: null,
    productionUrl: null,
    syncEnabled: true,
  },
];
