import type { InsertProject } from "../../shared/validators";

// AI Provider seed configs
export const SEED_AI_PROVIDERS = [
  {
    slug: "anthropic",
    displayName: "Anthropic",
    providerType: "anthropic" as const,
    isEnabled: false,
    defaultForRole: "architect" as const,
    modelTiers: { builder: "claude-sonnet-4-6", architect: "claude-opus-4-6" },
    config: {},
    displayOrder: 1,
    availableModels: {
      architect: [
        { id: "claude-opus-4-6", name: "Claude Opus 4.6", tier: "flagship" },
        { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", tier: "balanced" },
        { id: "claude-opus-4-5", name: "Claude Opus 4.5", tier: "previous" },
      ],
      builder: [
        { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", tier: "flagship" },
        { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", tier: "fast" },
        { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", tier: "previous" },
      ],
    },
  },
  {
    slug: "claude-code",
    displayName: "Claude Code",
    providerType: "claude-code" as const,
    isEnabled: false,
    modelTiers: { builder: "claude-code-opus" },
    config: {},
    displayOrder: 2,
    availableModels: {
      builder: [
        { id: "claude-code-opus", name: "Claude Code (Opus 4.6)", tier: "flagship" },
        { id: "claude-code-sonnet", name: "Claude Code (Sonnet 4.6)", tier: "fast" },
      ],
    },
  },
  {
    slug: "kimi",
    displayName: "Kimi (Moonshot)",
    providerType: "kimi" as const,
    isEnabled: false,
    modelTiers: { builder: "kimi-k2.5", architect: "kimi-k2.5" },
    config: { baseUrl: "https://api.moonshot.cn/v1" },
    displayOrder: 3,
    availableModels: {
      architect: [
        { id: "kimi-k2.5", name: "Kimi K2.5", tier: "flagship" },
        { id: "kimi-k2-thinking", name: "Kimi K2 Thinking", tier: "reasoning" },
      ],
      builder: [
        { id: "kimi-k2.5", name: "Kimi K2.5", tier: "flagship" },
        { id: "kimi-k2", name: "Kimi K2", tier: "fast" },
        { id: "moonshot-v1-32k", name: "Moonshot v1 32K", tier: "legacy" },
      ],
    },
  },
  {
    slug: "google",
    displayName: "Google (Gemini)",
    providerType: "google" as const,
    isEnabled: false,
    modelTiers: { builder: "gemini-3-flash", architect: "gemini-3.1-pro" },
    config: {},
    displayOrder: 4,
    availableModels: {
      architect: [
        { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", tier: "flagship" },
        { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", tier: "balanced" },
      ],
      builder: [
        { id: "gemini-3-flash", name: "Gemini 3 Flash", tier: "flagship" },
        { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", tier: "fast" },
        { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", tier: "legacy" },
      ],
    },
  },
  {
    slug: "deepseek",
    displayName: "DeepSeek",
    providerType: "deepseek" as const,
    isEnabled: false,
    modelTiers: { builder: "deepseek-chat", architect: "deepseek-reasoner" },
    config: { baseUrl: "https://api.deepseek.com/v1" },
    displayOrder: 5,
    availableModels: {
      architect: [
        { id: "deepseek-reasoner", name: "DeepSeek R1", tier: "reasoning" },
        { id: "deepseek-chat", name: "DeepSeek V3", tier: "balanced" },
      ],
      builder: [
        { id: "deepseek-chat", name: "DeepSeek V3", tier: "flagship" },
        { id: "deepseek-reasoner", name: "DeepSeek R1", tier: "reasoning" },
      ],
    },
  },
  {
    slug: "groq",
    displayName: "Groq",
    providerType: "groq" as const,
    isEnabled: false,
    modelTiers: { builder: "llama-3.3-70b-versatile" },
    config: { baseUrl: "https://api.groq.com/openai/v1" },
    displayOrder: 6,
    availableModels: {
      builder: [
        { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", tier: "flagship" },
        { id: "deepseek-r1-distill-llama-70b", name: "DeepSeek R1 Distill 70B", tier: "reasoning" },
        { id: "qwen-qwq-32b", name: "Qwen QwQ 32B", tier: "fast" },
      ],
    },
  },
  {
    slug: "openai",
    displayName: "OpenAI",
    providerType: "openai" as const,
    isEnabled: false,
    modelTiers: { builder: "gpt-4o", architect: "gpt-4o" },
    config: {},
    displayOrder: 7,
    availableModels: {
      architect: [
        { id: "gpt-4o", name: "GPT-4o", tier: "flagship" },
        { id: "gpt-4.1", name: "GPT-4.1", tier: "coding" },
      ],
      builder: [
        { id: "gpt-4o", name: "GPT-4o", tier: "flagship" },
        { id: "gpt-4.1-mini", name: "GPT-4.1 Mini", tier: "fast" },
        { id: "gpt-4.1", name: "GPT-4.1", tier: "coding" },
      ],
    },
  },
  {
    slug: "replit",
    displayName: "Replit Agent",
    providerType: "replit" as const,
    isEnabled: false,
    defaultForRole: "builder" as const,
    modelTiers: { builder: "replit-agent" },
    config: {},
    displayOrder: 8,
    availableModels: {
      builder: [
        { id: "replit-agent", name: "Replit Agent (Claude Sonnet)", tier: "flagship" },
      ],
    },
  },
];

export const SEED_PROJECTS: InsertProject[] = [
  {
    slug: "triadblue",
    displayName: "TRIADBLUE",
    description: "Core platform and ecosystem hub",
    githubRepo: "triadblue",
    colorPrimary: "#0000FF",
    colorAccent: "#FF44CC",
    iconUrl: "/assets/brands/triadblue/icon.png",
    status: "active",
    displayOrder: 0,
    visible: true,
    tags: ["core", "platform"],
    subdomainUrl: "triadblue.com",
    productionUrl: "https://triadblue.com",
    syncEnabled: true,
  },
  {
    slug: "consoleblue",
    displayName: "ConsoleBlue",
    description: "Central management dashboard for the TriadBlue ecosystem",
    githubRepo: "consoleblue",
    colorPrimary: "#FF44CC",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/consoleblue/icon.png",
    status: "active",
    displayOrder: 1,
    visible: true,
    tags: ["dashboard", "admin"],
    subdomainUrl: "console.blue",
    productionUrl: "https://console.blue",
    syncEnabled: true,
  },
  {
    slug: "linkblue",
    displayName: "LINKBlue",
    description: "Website monitoring and health tracking panel",
    githubRepo: "linkblue",
    colorPrimary: "#2073E3",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/linkblue/icon.png",
    status: "active",
    displayOrder: 2,
    visible: true,
    tags: ["monitoring", "health"],
    subdomainUrl: "linkblue.triadblue.com",
    productionUrl: "https://linkblue.triadblue.com",
    syncEnabled: true,
  },
  {
    slug: "hostsblue",
    displayName: "hostsblue",
    description: "Web hosting and infrastructure management",
    githubRepo: "hostsblue",
    colorPrimary: "#008060",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/hostsblue/icon.png",
    status: "active",
    displayOrder: 3,
    visible: true,
    tags: ["hosting", "infrastructure"],
    subdomainUrl: "hostsblue.com",
    productionUrl: "https://hostsblue.com",
    syncEnabled: true,
  },
  {
    slug: "swipesblue",
    displayName: "swipesblue",
    description: "Payment processing and transaction management",
    githubRepo: "swipesblue",
    colorPrimary: "#374151",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/swipesblue/icon.png",
    status: "active",
    displayOrder: 4,
    visible: true,
    tags: ["payments", "transactions"],
    subdomainUrl: "swipesblue.com",
    productionUrl: "https://swipesblue.com",
    syncEnabled: true,
  },
  {
    slug: "businessblueprint",
    displayName: "businessblueprint",
    description:
      "AI-powered business planning and digital assessment platform",
    githubRepo: "businessblueprint",
    colorPrimary: "#F97316",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/businessblueprint/icon.png",
    status: "active",
    displayOrder: 5,
    visible: true,
    tags: ["business-planning", "ai", "assessment"],
    subdomainUrl: null,
    productionUrl: null,
    syncEnabled: true,
  },
  {
    slug: "scansblue",
    displayName: "scansblue",
    description: "Security scanning and analysis tools",
    githubRepo: "scansblue",
    colorPrimary: "#A00028",
    colorAccent: "#0000FF",
    iconUrl: "/assets/brands/scansblue/icon.png",
    status: "development",
    displayOrder: 6,
    visible: true,
    tags: ["security", "scanning"],
    subdomainUrl: null,
    productionUrl: null,
    syncEnabled: true,
  },
];
